version: '3'
services:
  study-mate-ui:
    container_name: ui
    build: study-mate-ui
    ports:
      - 80:3000
    depends_on:
      - study-mate-api
  study-mate-api:
    container_name: api
    build: StudyMate.API
    ports:
      - 5000:5000
    depends_on:
      - study-mate-postgres
  study-mate-postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=StudyMateDb