name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  StudyMateUiBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: ./study-mate-ui
          file: ./study-mate-ui/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/study-mate-ui:latest

  StudyMateApiBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: ./StudyMate.API
          file: ./StudyMate.API/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/study-mate-api:latest

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - StudyMateUiBuild
      - StudyMateApiBuild
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        with:
          webhook_url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
